routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\PaySalaryController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\AttdanceController;
use App\Http\Controllers\SettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/', function () {
     return view('Auth.login');
});

//Frontend load
Route::get('main', 'App\Http\Controllers\FrontEndController@showHome') -> name('home.show');
Route::get('blog', 'App\Http\Controllers\FrontEndController@showBlog') -> name('blog.show');
Route::get('contact', 'App\Http\Controllers\FrontEndController@showContact') -> name('contact.show');
Route::get('about', 'App\Http\Controllers\FrontEndController@showAbout') -> name('about.show');
Route::get('cart', 'App\Http\Controllers\FrontEndController@showCart') -> name('cart.show');


//Employee routes here
Route::get('show-employee', 'App\Http\Controllers\EmployeeController@showEmployee') -> name('show.employee');
Route::get('add-employee', 'App\Http\Controllers\EmployeeController@create') -> name('add.employee');
Route::post('insert-employee', 'App\Http\Controllers\EmployeeController@store');
Route::get('single-employee/{id}', 'App\Http\Controllers\EmployeeController@viewSingle') -> name('single.employee');

Route::delete('delete-employee/{id}', 'App\Http\Controllers\EmployeeController@destroy') -> name('destroy.employee');
Route::get('edit-employee/{id}', 'App\Http\Controllers\EmployeeController@edit') -> name('edit.employee');
Route::put('update-employee/{id}', 'App\Http\Controllers\EmployeeController@update') -> name('update.employee');

//Customer routes
Route::resource('customer', CustomerController::class);

//supplier Route
Route::resource('supplier', SupplierController::class);

//Salary Route
Route::resource('salary', SalaryController::class);
//Pay Salary Route
Route::resource('pay_salary', PaySalaryController::class);

//Category Route
Route::resource('category', CategoryController::class);

//Product Route
Route::resource('product', ProductController::class);

//Expense Route
Route::resource('expense', ExpenseController::class);

//Today expense
Route::get('today-expense', 'App\Http\Controllers\ExpenseController@TodayExpense') -> name('today.expense');

//Monthly Expense
Route::get('monthly-expense', 'App\Http\Controllers\ExpenseController@MonthlyExpense') -> name('monthly.expense');
//Yearly Expense
Route::get('yearly-expense', 'App\Http\Controllers\ExpenseController@YearlyExpense') -> name('yearly.expense');

//January Expense Route
Route::get('january-expense', 'App\Http\Controllers\ExpenseController@JanuaryExpense') -> name('january.expense');

//February Expense Route
Route::get('february-expense', 'App\Http\Controllers\ExpenseController@FebruaryExpense') -> name('february.expense');

//March Expense Route
Route::get('march-expense', 'App\Http\Controllers\ExpenseController@MarchExpense') -> name('march.expense');

//April Expense Route
Route::get('april-expense', 'App\Http\Controllers\ExpenseController@AprilExpense') -> name('april.expense');

//May Expense Route
Route::get('may-expense', 'App\Http\Controllers\ExpenseController@MayExpense') -> name('may.expense');

//June Expense Route
Route::get('june-expense', 'App\Http\Controllers\ExpenseController@JuneExpense') -> name('june.expense');

//July Expense Route
Route::get('july-expense', 'App\Http\Controllers\ExpenseController@JulyExpense') -> name('july.expense');

//August Expense Route
Route::get('august-expense', 'App\Http\Controllers\ExpenseController@AugustExpense') -> name('august.expense');

//September Expense Route
Route::get('september-expense', 'App\Http\Controllers\ExpenseController@SeptemberExpense') -> name('september.expense');

//October Expense Route
Route::get('october-expense', 'App\Http\Controllers\ExpenseController@OctoberExpense') -> name('october.expense');

//November Expense Route
Route::get('noverber-expense', 'App\Http\Controllers\ExpenseController@NoverberExpense') -> name('noverber.expense');

//December Expense Route
Route::get('december-expense', 'App\Http\Controllers\ExpenseController@DecemberExpense') -> name('december.expense');

//Attdance Route

Route::resource('attendence', 'App\Http\Controllers\AttdanceController');

//Setting Route
Route::get('setting', 'App\Http\Controllers\SettingController@Setting') -> name('setting.create');
Route::put('setting-update/{id}', 'App\Http\Controllers\SettingController@Update') -> name('setting.update');

//Elcel Import and export

Route::get('import-product', 'App\Http\Controllers\ProductController@ImportProduct') -> name('import.product');
Route::get('export', 'App\Http\Controllers\ProductController@export') -> name('export');
Route::post('import', 'App\Http\Controllers\ProductController@import') -> name('import');



//Pos ROutes
Route::get('pos', 'App\Http\Controllers\PosController@index') -> name('pos');

Route::get('pending/order', 'App\Http\Controllers\PosController@PendingOrder') -> name('pending.order');
Route::get('success/order', 'App\Http\Controllers\PosController@SuccessOrder') -> name('success.order');
Route::get('view-order-status/{id}', 'App\Http\Controllers\PosController@ViewOrder') -> name('view.order');
Route::get('pos-done/{id}', 'App\Http\Controllers\PosController@PosDone') -> name('pos.order');

//Cart Route here

Route::post('add-cart', 'App\Http\Controllers\CartController@index') -> name('cart.add');
Route::post('update-cart/{rowId}', 'App\Http\Controllers\CartController@update') -> name('cart.update');
Route::get('remove-cart/{rowId}', 'App\Http\Controllers\CartController@destroy') -> name('cart.remove');
Route::post('create-invoice', 'App\Http\Controllers\CartController@CreateInvoice') -> name('invoice.create');
Route::post('final-invoice', 'App\Http\Controllers\CartController@finalInvoice') -> name('invoice.final');

app/Models/supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $guarded =[];
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{


     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_supplier = Supplier::latest() -> get();
        return view('admin.supplier.index', compact('all_supplier') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.supplier.add');


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this-> validate($request , [
            'name' => 'required|max:255',
            'email' => 'required|unique:suppliers|max:255',
            'phone' => 'required|unique:suppliers|max:15',
            'address' => 'required',
            'shope_name' => 'required',
            'account_holder' => 'required',

            'account_number' => 'required|max:30',
            'bank_name' => 'required',
            'bank_branch' => 'required',

            'photo' => 'required',

        ]);

        if( $request -> hasFile('photo')){

            $picture = $request -> file('photo');
            $picture_name = md5(time().rand()).'.'. $picture -> getClientOriginalExtension();
            $picture -> move(public_path('media/suppliers_photo'), $picture_name );

           }

       Supplier::create([
            'name' => $request -> name,
            'email' => $request -> email,
            'phone' => $request -> phone,
            'address' => $request -> address,
            'photo' => $picture_name,
            'shope_name' => $request -> shope_name,
            'account_holder' => $request -> account_holder,
            'account_number' => $request -> account_number,
            'bank_name' => $request -> bank_name,
            'bank_branch' => $request -> bank_branch,
            'type' => $request -> type,
           'city' => $request -> city,
        ]);

        return redirect() -> back() -> with('success', 'Supplier added successfull');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/supplier/add.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">



				<div class="row">
					<div class="col-md-8 offset-2">
                        @include('validate')
                        <div class="card pl-3 pr-3">
                            <div class="card-header">
                                <h4 class="card-title">Add Supplier</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('supplier.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
         



                                    <div class="form-group">
                                        <label>Name</label>
                                        <input name="name" type="text" class="form-control" placeholder="Name" >
                                    </div>
                                    <div class="form-group">
                                        <label>E-mail</label>
                                        <input name="email" type="text" class="form-control" placeholder="E-mail" >
                                    </div>
                                    <div class="form-group">
                                        <label>Phone</label>
                                        <input name="phone" type="text" class="form-control" placeholder="Phone" >
                                    </div>

                                    <div class="form-group">
                                        <label>Address</label>
                                        <input name="address" type="text" class="form-control" placeholder="Address" >
                                    </div>

                                    <div class="form-group">
                                        <label>Shope Name</label>
                                        <input name="shope_name" type="text" class="form-control" placeholder="Shope Name" >
                                    </div>

                                     
        <p class="card-text"> </p>
       
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">

                                    <div class="form-group">
                                        <label>Account Holder</label>
                                        <input name="account_holder" type="text" class="form-control" placeholder="Account Holder" >
                                    </div>
                                    <div class="form-group">
                                        <label>Accoutnt Number</label>
                                        <input name="account_number" type="text" class="form-control" placeholder="Account Number">
                                    </div>

                                    <div class="form-group">
                                        <label>Bank Name</label>
                                        <input name="bank_name" type="text" class="form-control" placeholder="Bank Name">
                                    </div>

                                    <div class="form-group">
                                        <label>Bank Branch</label>
                                        <input name="bank_branch" type="text" class="form-control" placeholder="Back Branch">
                                    </div>

                                    <div class="form-group">
                                        <label>City</label>
                                        <input name="city" type="text" class="form-control" placeholder="City">
                                    </div>

                                    <div class="form-group">
                                        <label>Supplier Type</label>
                                       <select name="type" id="" class=" form-control">
                                           <option disabled="" selected=""></option>
                                           <option value="1">Distributor</option>
                                           <option value="2">Whole Cell</option>
                                           <option value="3">Brochure</option>
                                       </select>
                                    </div>

                                    <div class="form-group">

                                        <img class="" id="image" src="#"><label>Photo</label> <br>

                                        <input type="file" class="" name="photo" accept="image/*" class="upload" onchange="readURL(this);">
                                    </div>



                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

				</div>


			</div>
		</div>
        <!-- /Page Wrapper -->

        {{-- Image  --}}
        <script type="text/javascript">
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function (e){
                        $('#image')
                            .attr('src', e.target.result)
                            .width(80)
                            .height(80);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
@endsection

resources/views/admin/supplier/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">



				<div class="row">
					<div class="col-md-8 offset-2">
                        @include('validate')
                        <div class="card pl-3 pr-3">
                            <div class="card-header">
                                <h4 class="card-title text-primary">Update {{ ($all_data -> name) }}'s Information</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('update.employee',$all_data -> id ) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('put')

                                    <div class="form-group">
                                        <label>Name</label>
                                        <input name="name" type="text" class="form-control" value="{{ ($all_data -> name) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>E-mail</label>
                                        <input name="email" type="text" class="form-control" placeholder="E-mail" value="{{ ($all_data -> email) }}" >
                                    </div>
                                    <div class="form-group">
                                        <label>Phone</label>
                                        <input name="phone" type="text" class="form-control" placeholder="Phone" value="{{ ($all_data -> phone) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Exprience</label>
                                        <input name="exprience" type="text" class="form-control" placeholder="Exprience" value="{{ ($all_data -> exprience) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Address</label>
                                        <input name="address" type="text" class="form-control" placeholder="Address" value="{{ ($all_data -> address) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>NID NO</label>
                                        <input name="nid_no" type="text" class="form-control" placeholder="National ID Number" value="{{ ($all_data -> nid_no) }}">
                                    </div>


                                    <div class="form-group">
                                        <label>Salary</label>
                                        <input name="salary" type="text" class="form-control" placeholder="Salary" value="{{ ($all_data -> salary) }}">
                                    </div>

                                    <div class="form-group">
                                        <label>Vacation</label>
                                        <input name="vacation" type="text" class="form-control" placeholder="Vacation" value="{{ ($all_data -> vacation) }}">
                                    </div>

                                    <div class="form-group">
                                        <label>City</label>
                                        <input name="city" type="text" class="form-control" placeholder="City" value="{{ ($all_data -> city) }}">
                                    </div>

                                    <div class="form-group">

 @if( !empty($all_data -> photo) )
                                            <img style="height: 100px; width: 100px;" src="{{ URL::to('/') }}/media/employee_photos/{{ $all_data -> photo }}" alt="">
                                            @endif <br>

                                            <input type="hidden" name="old_picture" value="{{ $all_data -> photo }}">

                                          
                                        <img class="" id="image" src="#"><label>Photo</label> 
                                        <br>
                                        
                                        



                                        <input type="file" name="new_picture" accept="image/*" class="upload" onchange="readURL(this);">
                                    </div>

                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

				</div>


			</div>
		</div>
        <!-- /Page Wrapper -->

        {{-- Image  --}}
        <script type="text/javascript">
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function (e){
                        $('#image')
                            .attr('src', e.target.result)
                            .width(80)
                            .height(80);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
@endsection

resources/views/admin/supplier/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">


                <div class="card">
                    @include('validate')
                    <div class="card-header">
                    <h2 class="card-title">All Supplier<a href="{{ route('supplier.create') }}"> <button class="btn btn-success"><i class="fe fe-user"></i>Add Supplier</button></a> </h2>

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data-table-data" class="table table-striped mb-0">
                                <thead>


                                    <tr>
                                        <th>SL</th>

                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Address</th>
                                        <th>Image</th>

                                        <th>Shope Name</th>
                                        <th>City</th>

                                        <th>Acion</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($all_supplier as $supplier)
                                    <tr>
                                        <td>{{ $loop -> index+1 }}</td>



                                        <td>{{ $supplier -> name }}</td>
                                        <td>{{ $supplier -> phone }}</td>
                                        <td>{{ $supplier -> address }}</td>
                                        <td>
                                            @if( !empty($supplier -> photo) )
                                            <img style="height: 50px; width: 50px;" src="{{ URL::to('/') }}/media/suppliers_photo/{{ $supplier -> photo }}" alt="">
                                            @endif


                                        </td>

                                        <td>{{ $supplier -> shope_name }}</td>
                                        <td>{{ $supplier -> city }}</td>

                                        <td>

                                            <a class=" btn btn-primary btn-sm" href="">View</a>

                                            <a class=" btn btn-warning btn-sm" href="">Edit</a>

                                            <form style="display: inline;" action="" method="POST">

                                                <button id="delete" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>




			</div>
		</div>

@endsection

resources/views/admin/supplier/show.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">


                <div class="card">
                    @include('validate')
                    <div class="card-header">
                        <h4 class="card-title">{{ $all_data -> name }}</h4>

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data-table-data" class="table table-striped mb-0">

                                @if( !empty($all_data -> photo) )
                                <img id="table_img" src="{{ URL::to('/') }}/media/employee_photos/{{ $all_data -> photo }}" alt="centered image">
                                @endif

                                <tbody class="text-center">
                                  <tr>
                                      <td>Name</td>
                                      <td>{{ $all_data -> name }}</td>
                                  </tr>

                                  <tr>
                                    <td>E-mail</td>
                                    <td>{{ $all_data -> email }}</td>
                                </tr>

                                <tr>
                                    <td>Phone Number</td>
                                    <td>{{ $all_data -> phone }}</td>
                                </tr>

                                <tr>
                                    <td>Address</td>
                                    <td>{{ $all_data -> address }}</td>
                                </tr>

                                <tr>
                                    <td>NID NO</td>
                                    <td>{{ $all_data -> nid_no }}</td>
                                </tr>

                                <tr>
                                    <td>Exprience</td>
                                    <td>{{ $all_data -> exprience }}</td>
                                </tr>

                                <tr>
                                    <td>Vacation</td>
                                    <td>{{ $all_data -> vacation }}</td>
                                </tr>

                                <tr>
                                    <td>City</td>
                                    <td>{{ $all_data -> city }}</td>
                                </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>




			</div>
		</div>

@endsection