routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\PaySalaryController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\AttdanceController;
use App\Http\Controllers\SettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/', function () {
     return view('Auth.login');
});

//Frontend load
Route::get('main', 'App\Http\Controllers\FrontEndController@showHome') -> name('home.show');
Route::get('blog', 'App\Http\Controllers\FrontEndController@showBlog') -> name('blog.show');
Route::get('contact', 'App\Http\Controllers\FrontEndController@showContact') -> name('contact.show');
Route::get('about', 'App\Http\Controllers\FrontEndController@showAbout') -> name('about.show');
Route::get('cart', 'App\Http\Controllers\FrontEndController@showCart') -> name('cart.show');


//Employee routes here
Route::get('show-employee', 'App\Http\Controllers\EmployeeController@showEmployee') -> name('show.employee');
Route::get('add-employee', 'App\Http\Controllers\EmployeeController@create') -> name('add.employee');
Route::post('insert-employee', 'App\Http\Controllers\EmployeeController@store');
Route::get('single-employee/{id}', 'App\Http\Controllers\EmployeeController@viewSingle') -> name('single.employee');

Route::delete('delete-employee/{id}', 'App\Http\Controllers\EmployeeController@destroy') -> name('destroy.employee');
Route::get('edit-employee/{id}', 'App\Http\Controllers\EmployeeController@edit') -> name('edit.employee');
Route::put('update-employee/{id}', 'App\Http\Controllers\EmployeeController@update') -> name('update.employee');

//Customer routes
Route::resource('customer', CustomerController::class);

//supplier Route
Route::resource('supplier', SupplierController::class);

//Salary Route
Route::resource('salary', SalaryController::class);
//Pay Salary Route
Route::resource('pay_salary', PaySalaryController::class);

//Category Route
Route::resource('category', CategoryController::class);

//Product Route
Route::resource('product', ProductController::class);

//Expense Route
Route::resource('expense', ExpenseController::class);

//Today expense
Route::get('today-expense', 'App\Http\Controllers\ExpenseController@TodayExpense') -> name('today.expense');

//Monthly Expense
Route::get('monthly-expense', 'App\Http\Controllers\ExpenseController@MonthlyExpense') -> name('monthly.expense');
//Yearly Expense
Route::get('yearly-expense', 'App\Http\Controllers\ExpenseController@YearlyExpense') -> name('yearly.expense');

//January Expense Route
Route::get('january-expense', 'App\Http\Controllers\ExpenseController@JanuaryExpense') -> name('january.expense');

//February Expense Route
Route::get('february-expense', 'App\Http\Controllers\ExpenseController@FebruaryExpense') -> name('february.expense');

//March Expense Route
Route::get('march-expense', 'App\Http\Controllers\ExpenseController@MarchExpense') -> name('march.expense');

//April Expense Route
Route::get('april-expense', 'App\Http\Controllers\ExpenseController@AprilExpense') -> name('april.expense');

//May Expense Route
Route::get('may-expense', 'App\Http\Controllers\ExpenseController@MayExpense') -> name('may.expense');

//June Expense Route
Route::get('june-expense', 'App\Http\Controllers\ExpenseController@JuneExpense') -> name('june.expense');

//July Expense Route
Route::get('july-expense', 'App\Http\Controllers\ExpenseController@JulyExpense') -> name('july.expense');

//August Expense Route
Route::get('august-expense', 'App\Http\Controllers\ExpenseController@AugustExpense') -> name('august.expense');

//September Expense Route
Route::get('september-expense', 'App\Http\Controllers\ExpenseController@SeptemberExpense') -> name('september.expense');

//October Expense Route
Route::get('october-expense', 'App\Http\Controllers\ExpenseController@OctoberExpense') -> name('october.expense');

//November Expense Route
Route::get('noverber-expense', 'App\Http\Controllers\ExpenseController@NoverberExpense') -> name('noverber.expense');

//December Expense Route
Route::get('december-expense', 'App\Http\Controllers\ExpenseController@DecemberExpense') -> name('december.expense');

//Attdance Route

Route::resource('attendence', 'App\Http\Controllers\AttdanceController');

//Setting Route
Route::get('setting', 'App\Http\Controllers\SettingController@Setting') -> name('setting.create');
Route::put('setting-update/{id}', 'App\Http\Controllers\SettingController@Update') -> name('setting.update');

//Elcel Import and export

Route::get('import-product', 'App\Http\Controllers\ProductController@ImportProduct') -> name('import.product');
Route::get('export', 'App\Http\Controllers\ProductController@export') -> name('export');
Route::post('import', 'App\Http\Controllers\ProductController@import') -> name('import');



//Pos ROutes
Route::get('pos', 'App\Http\Controllers\PosController@index') -> name('pos');

Route::get('pending/order', 'App\Http\Controllers\PosController@PendingOrder') -> name('pending.order');
Route::get('success/order', 'App\Http\Controllers\PosController@SuccessOrder') -> name('success.order');
Route::get('view-order-status/{id}', 'App\Http\Controllers\PosController@ViewOrder') -> name('view.order');
Route::get('pos-done/{id}', 'App\Http\Controllers\PosController@PosDone') -> name('pos.order');

//Cart Route here

Route::post('add-cart', 'App\Http\Controllers\CartController@index') -> name('cart.add');
Route::post('update-cart/{rowId}', 'App\Http\Controllers\CartController@update') -> name('cart.update');
Route::get('remove-cart/{rowId}', 'App\Http\Controllers\CartController@destroy') -> name('cart.remove');
Route::post('create-invoice', 'App\Http\Controllers\CartController@CreateInvoice') -> name('invoice.create');
Route::post('final-invoice', 'App\Http\Controllers\CartController@finalInvoice') -> name('invoice.final');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory;


    protected $guarded = [];

    public function catagories(){

        return $this-> belongsTo(Category::class, 'cat_id', 'id');
    }


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Http\Request;

use App\Exports\ProductExport;
use App\Imports\ProductImport;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{


     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_product = Product::latest() -> get();
        return view('admin.product.index', compact('all_product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $all_category = Category::latest() -> get();
        $all_supplier = Supplier::latest() -> get();
        return view('admin.product.add', compact('all_category', 'all_supplier'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this-> validate($request , [
            'product_name' => 'required',
            'cat_id' => 'required',
            'sup_id' => 'required',
            'product_code' => 'required|unique:products|max:255',
            'product_garage' => 'required',
            'product_route' => 'required',
            'buy_date' => 'required',
            'expire_date' => 'required',
            'buying_price' => 'required',
            'selling_price' => 'required',

        ]);

        if( $request -> hasFile('photo')){

            $picture = $request -> file('photo');
            $picture_name = md5(time().rand()).'.'. $picture -> getClientOriginalExtension();
            $picture -> move(public_path('media/product_photos'), $picture_name );

           }

        Product::create([
            'product_name' => $request -> product_name,
            'cat_id' => $request -> cat_id,
            'sup_id' => $request -> sup_id,
            'product_code' => $request -> product_code,
            'product_garage' => $request -> product_garage,
            'product_route' => $request -> product_route,
            'product_image' => $picture_name ,
            'buy_date' => $request -> buy_date,
            'expire_date' => $request -> expire_date,
            'buying_price' => $request -> buying_price,
           'selling_price' => $request -> selling_price,
        ]);

        return redirect() -> back() -> with('success', 'Product added successfull');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function ImportProduct(){

        return view('admin.product.import_product');
    }

    public function export()
    {
        return Excel::download(new ProductExport, 'products.xlsx');
    }

    public function import(Request $request)
    {
        $import = Excel::import(new ProductImport, $request -> file('import_file'));

        return redirect() -> route('product.index') -> with('success', 'Product added successfull');


    }

}

resources/views/admin/product/add.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">



				<div class="row">
					<div class="col-md-8 offset-2">
                        @include('validate')
                        <div class="card pl-3 pr-3">
                            <div class="card-header">
                                <h4 class="card-title">Add Product


                                    <a class="btn btn-primary btn-sm pull-right" href="{{ route('product.index') }}">All Product</a>
                                    <a class="btn btn-success btn-sm pull-right mr-2" href="{{ route('import.product') }}">Import Product</a>
                                </h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf

 <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">



                                    <div class="form-group">
                                        <label>Product Name</label>
                                        <input name="product_name" type="text" class="form-control" placeholder="Product Name" >
                                    </div>

                                    <div class="form-group">
                                        <label>Product Code</label>
                                        <input name="product_code" type="text" class="form-control" placeholder="Product Name" >
                                    </div>
                                    <div class="form-group">
                                        <label>Category Name</label>
                                       <select name="cat_id" id="" class=" form-control">
                                           <option disabled="" selected=""></option>
                                          @foreach($all_category  as $category)
                                          <option value="{{ $category -> id }}">{{ $category -> cat_name }}</option>
                                          @endforeach

                                       </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Supplier Name</label>
                                        <select name="sup_id" id="" class=" form-control">
                                            <option disabled="" selected=""></option>
                                           @foreach($all_supplier  as $supplier)
                                           <option value="{{ $supplier -> id }}">{{ $supplier -> name }}</option>
                                           @endforeach

                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Godaun</label>
                                        <input name="product_garage" type="text" class="form-control" placeholder="Godaun Number" >
                                    </div>

                        <p class="card-text"> </p>
       
                    </div>
                    </div>
                </div>


   <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">


                                    <div class="form-group">
                                        <label>Product Route</label>
                                        <input name="product_route" type="text" class="form-control" placeholder="Product Route" >
                                    </div>
                                    <div class="form-group">
                                        <label>Buying Date</label>
                                        <input name="buy_date" type="date" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Expire Date</label>
                                        <input name="expire_date" type="date" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label>Buying Price</label>
                                        <input name="buying_price" type="text" class="form-control" placeholder="Buying Price">
                                    </div>

                                    <div class="form-group">
                                        <label>Selling Price</label>
                                        <input name="selling_price" type="text" class="form-control" placeholder="Selling Price">
                                    </div>



                                    <div class="form-group">

                                        <img class="" id="image" src="#"><label>Product Image</label> <br>

                                        <input type="file" class="" name="photo" accept="image/*" class="upload" onchange="readURL(this);">
                                    </div>

                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

				</div>


			</div>
		</div>
        <!-- /Page Wrapper -->

        {{-- Image  --}}
        <script type="text/javascript">
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function (e){
                        $('#image')
                            .attr('src', e.target.result)
                            .width(80)
                            .height(80);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">



				<div class="row">
					<div class="col-md-8 offset-2">
                        @include('validate')
                        <div class="card pl-3 pr-3">
                            <div class="card-header">
                                <h4 class="card-title text-primary">Update {{ ($all_data -> name) }}'s Information</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('update.employee',$all_data -> id ) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('put')

                                    <div class="form-group">
                                        <label>Name</label>
                                        <input name="name" type="text" class="form-control" value="{{ ($all_data -> name) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>E-mail</label>
                                        <input name="email" type="text" class="form-control" placeholder="E-mail" value="{{ ($all_data -> email) }}" >
                                    </div>
                                    <div class="form-group">
                                        <label>Phone</label>
                                        <input name="phone" type="text" class="form-control" placeholder="Phone" value="{{ ($all_data -> phone) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Exprience</label>
                                        <input name="exprience" type="text" class="form-control" placeholder="Exprience" value="{{ ($all_data -> exprience) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Address</label>
                                        <input name="address" type="text" class="form-control" placeholder="Address" value="{{ ($all_data -> address) }}">
                                    </div>
                                    <div class="form-group">
                                        <label>NID NO</label>
                                        <input name="nid_no" type="text" class="form-control" placeholder="National ID Number" value="{{ ($all_data -> nid_no) }}">
                                    </div>


                                    <div class="form-group">
                                        <label>Salary</label>
                                        <input name="salary" type="text" class="form-control" placeholder="Salary" value="{{ ($all_data -> salary) }}">
                                    </div>

                                    <div class="form-group">
                                        <label>Vacation</label>
                                        <input name="vacation" type="text" class="form-control" placeholder="Vacation" value="{{ ($all_data -> vacation) }}">
                                    </div>

                                    <div class="form-group">
                                        <label>City</label>
                                        <input name="city" type="text" class="form-control" placeholder="City" value="{{ ($all_data -> city) }}">
                                    </div>

                                    <div class="form-group">

 @if( !empty($all_data -> photo) )
                                            <img style="height: 100px; width: 100px;" src="{{ URL::to('/') }}/media/employee_photos/{{ $all_data -> photo }}" alt="">
                                            @endif <br>

                                            <input type="hidden" name="old_picture" value="{{ $all_data -> photo }}">

                                          
                                        <img class="" id="image" src="#"><label>Photo</label> 
                                        <br>
                                        
                                        



                                        <input type="file" name="new_picture" accept="image/*" class="upload" onchange="readURL(this);">
                                    </div>

                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

				</div>


			</div>
		</div>
        <!-- /Page Wrapper -->

        {{-- Image  --}}
        <script type="text/javascript">
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function (e){
                        $('#image')
                            .attr('src', e.target.result)
                            .width(80)
                            .height(80);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
@endsection

resources/views/admin/product/import_product.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container">



				<div class="row">
					<div class="col-md-8 offset-2">
                        @include('validate')
                        <div class="card pl-3 pr-3">
                            <div class="card-header">
                                <h4 class="card-title">Products Import
                                <a class="pull-right btn btn-success btn-sm" href="{{ route('export') }}">Download <strong>Xlsx</strong></a>
                                </h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('import') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <label><strong>Xlsx</strong> File Import</label>
                                        <input name="import_file" type="file" class="form-control" >
                                    </div>


                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>

                            <small class="text-danger p-2">
                                <strong>
                                    Please download the xlsx file and clear it | Now you write your all products by listing and import it again | Thank You.
                                </strong>
                            </small>
                        </div>
                    </div>

				</div>


			</div>
		</div>
        <!-- /Page Wrapper -->

        {{-- Image  --}}
        <script type="text/javascript">
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function (e){
                        $('#image')
                            .attr('src', e.target.result)
                            .width(80)
                            .height(80);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">


                <div class="card">
                    @include('validate')
                    <div class="card-header">
                        <h4 class="card-title">All Products <a class="btn btn-primary btn-sm pull-right" href="{{ route('product.create') }}">Add Product</a></h4>

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data-table-data" class="table table-striped mb-0">
                                <thead>


                                    <tr>
                                        <th>SL</th>

                                        <th>Name</th>
                                        <th>Code</th>
                                        <th>Selling Price</th>
                                        <th>Image</th>

                                        <th>Garage</th>
                                        <th>Route</th>

                                        <th>Acion</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($all_product as $product)
                                    <tr>
                                        <td>{{ $loop -> index+1 }}</td>



                                        <td>{{ $product -> product_name }}</td>
                                        <td>{{ $product -> product_code }}</td>
                                        <td>{{ $product -> selling_price }}</td>
                                        <td>
                                            @if( !empty($product -> product_image) )
                                            <img style="height: 50px; width: 50px;" src="{{ URL::to('/') }}/media/product_photos/{{ $product -> product_image }}" alt="">
                                            @endif


                                        </td>

                                        <td>{{ $product -> product_garage }}</td>
                                        <td>{{ $product -> product_route }}</td>

                                        <td>

                                            <a class=" btn btn-primary btn-sm" href="">View</a>

                                            <a class=" btn btn-warning btn-sm" href="">Edit</a>

                                            <form style="display: inline;" action="" method="POST">

                                                <button id="delete" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>




			</div>
		</div>

@endsection

resources/views/admin/product/show.blade.php
@extends('admin.layouts.app')

@section('main-content')
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			<div class="content container-fluid">


                <div class="card">
                    @include('validate')
                    <div class="card-header">
                        <h4 class="card-title">{{ $all_data -> name }}</h4>

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data-table-data" class="table table-striped mb-0">

                                @if( !empty($all_data -> photo) )
                                <img id="table_img" src="{{ URL::to('/') }}/media/employee_photos/{{ $all_data -> photo }}" alt="centered image">
                                @endif

                                <tbody class="text-center">
                                  <tr>
                                      <td>Name</td>
                                      <td>{{ $all_data -> name }}</td>
                                  </tr>

                                  <tr>
                                    <td>E-mail</td>
                                    <td>{{ $all_data -> email }}</td>
                                </tr>

                                <tr>
                                    <td>Phone Number</td>
                                    <td>{{ $all_data -> phone }}</td>
                                </tr>

                                <tr>
                                    <td>Address</td>
                                    <td>{{ $all_data -> address }}</td>
                                </tr>

                                <tr>
                                    <td>NID NO</td>
                                    <td>{{ $all_data -> nid_no }}</td>
                                </tr>

                                <tr>
                                    <td>Exprience</td>
                                    <td>{{ $all_data -> exprience }}</td>
                                </tr>

                                <tr>
                                    <td>Vacation</td>
                                    <td>{{ $all_data -> vacation }}</td>
                                </tr>

                                <tr>
                                    <td>City</td>
                                    <td>{{ $all_data -> city }}</td>
                                </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>




			</div>
		</div>

@endsection